# Generated by Django 3.0.4 on 2020-04-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_item_name', models.CharField(max_length=50, unique=True)),
                ('or_item_quantity', models.FloatField()),
                ('or_total_price', models.FloatField()),
            ],
        ),
    ]
