# Generated by Django 3.0.4 on 2020-04-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
